### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by TheTw3ys** [HGLabor/client-issues#170]
Während des öffnens des Clients gibt es keine Probleme, allerdings sobald Ich versuche einem Server oder einer Singleplayer Welt beizutreten stürzt der Client mit der Fehlermeldung:
![Unbenannt2](https://user-images.githubusercontent.com/44274116/103176128-6780dc00-486f-11eb-9ba9-3a4dce011de2.PNG)

**Comment by TheTw3ys** [comment]
### Hier noch die volle Fehlermeldung:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLLoadingPlugin (latest.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 27.12.20 18:13
Description: Unexpected error

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at net.minecraft.client.settings.GameSettings.func_100015_a(GameSettings.java:369)
	at net.minecraft.client.renderer.EntityRenderer.func_78481_a(EntityRenderer.java:648)
	at net.minecraft.client.renderer.EntityRenderer.func_78479_a(EntityRenderer.java:936)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1612)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1580)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1372)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at net.minecraft.client.settings.GameSettings.func_100015_a(GameSettings.java:369)
	at net.minecraft.client.renderer.EntityRenderer.func_78481_a(EntityRenderer.java:648)
	at net.minecraft.client.renderer.EntityRenderer.func_78479_a(EntityRenderer.java:936)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1612)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1580)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['meppi'/8373483, l='MpServer', x=-23,68, y=70,05, z=1,28]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -24,00,70,00,1,00 - World: (-24,70,1), Chunk: (at 8,4,1 in -2,0; contains blocks -32,0,0 to -17,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 588071575 game time, 276250 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['meppi'/8373483, l='MpServer', x=-23,68, y=70,05, z=1,28]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (Hypixel) <- vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:402)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 429023432 bytes (409 MB) / 1073741824 bytes (1024 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1722 Optifine OptiFine_1.8.9_HD_U_L5 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1722.jar) 
	UCHIJA	Forge{11.15.1.1722} [Minecraft Forge] (forge-1.8.9-11.15.1.1722.jar) 
	Loaded coremods (and transformers): 
FMLLoadingPlugin (latest.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14736 Compatibility Profile Context 20.11.1 27.20.12033.2007' Renderer: 'AMD Radeon RX 5700 XT'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1722
	LWJGL: 2.9.4
	OpenGL: AMD Radeon RX 5700 XT GL version 4.6.14736 Compatibility Profile Context 20.11.1 27.20.12033.2007, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Mizunos 16 Craft JE_1.16.4-1.0.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
	OptiFine Version: OptiFine_1.8.9_HD_U_L5
	OptiFine Build: 20191204-143016
	Render Distance Chunks: 11
	Mipmaps: 3
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.14736 Compatibility Profile Context 20.11.1 27.20.12033.2007
	OpenGlRenderer: AMD Radeon RX 5700 XT
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12

**Comment by DasToastBrotGHG** [comment]
Can you maybe write into your message how to reconstruct this Error and maybe a copy of your NoRisk-Client Settings or a copy of your options.txt file? I think this could be helpful to see where the error has come from. Btw. sorry for my bad English

**Comment by TheTw3ys** [comment]
The bug happens when joining a world or a server. I don´t use any other mods than optifine. Sry for my bad english, too.

**Comment by TheTw3ys** [comment]
The options.txt file 
[options.txt](https://github.com/copyandexecute/noriskclient-issues/files/5744912/options.txt)

**Comment by TheTw3ys** [comment]
My Norisk-Folder

[norisk.zip](https://github.com/copyandexecute/noriskclient-issues/files/5744919/norisk.zip)

**Comment by TheTw3ys** [comment]
I hope I didn´t missed anything

**Comment by TheTw3ys** [comment]
Ah I tried it in Fullscreen and without
