### ISSUE TITLE
Absturz bei singleplayer

### ISSUE THREAD

**Issue by Someone-YT** [HGLabor/client-issues#224]
Bei mir war es oft so, dass wenn ich in eine Singleplayer Welt gehen wollte, das Spiel abgestürzt ist. Ich weiß nicht ob das schon gefixt wurde (wenn ja sorry für diesen Bugreport xdd) und ja xd

**Comment by Kolpixx** [comment]
Hey,

welche version benutzt du die non-forge oder die forge version und kannst du bitte den crash log senden ( "windows taste" + "r" dann "%appdata%" dann enter drücken ,dann in den .minecraft ortner gehen dann in den crash-report ortner reingehen hier sollte die crash log file drinne sein).

Mit freundlichen Grüßen
Kolpix

**Comment by Someone-YT** [comment]
Hey, 
ich verwende die forge Version. 
Der crashlog:  

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLLoadingPlugin (latest.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 04.02.21 09:42
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:414)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:47)
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:414)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:47)
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:414)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:47)
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:132)
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:87)
	at net.minecraft.nbt.CompressedStreamTools.func_74794_a(CompressedStreamTools.java:82)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:92)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:20)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:343)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:109)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:307)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:212)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:235)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 385479112 bytes (367 MB) / 671088640 bytes (640 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1722 Optifine OptiFine_1.8.9_HD_U_L5 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1722.jar) 
	UCHIJAA	Forge{11.15.1.1722} [Minecraft Forge] (forge-1.8.9-11.15.1.1722.jar) 
	Loaded coremods (and transformers): 
FMLLoadingPlugin (latest.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.8.9_HD_U_L5
	OptiFine Build: 20191204-143016
	Render Distance Chunks: 4
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.3.11672 Compatibility Profile Context
	OpenGlRenderer: ATI Radeon HD 4800 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

Mit freundlichen Grüßen
Paul (ja das mein rl Name xD)

**Comment by Kolpixx** [comment]
Hey,

benutzt du noch andere Mods ,wenn ja entferne sie mal und versuche es ohne die Mods. Und falls das nicht geht versuch mal das falls du es nicht gemacht hast: https://youtu.be/4dcUdz2Efdc?t=70

Mit freundlichen Grüßen
Kolpix
