### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by next361** [HGLabor/client-issues#40]
Sobald ich auf einen Server joinen möchte, dann crasht der Client bei mir.

Mods installiert:
den Client und Optifine.

was im Client an ist:
keystrokes,
fps,
cps,
coords,
togglesprint,
discordrpc,
nametag,
cosmetics.

und ich habe keinen Shader drin!

Der Fehler:
The game crashed whilst tesselating block model
Error: java.lang.ArrayIndexOutOfBoundsException: 8263
Exit Code: -1

Crashlog:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLLoadingPlugin (latest.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 17.12.20 10:52
Description: Tesselating block model

java.lang.ArrayIndexOutOfBoundsException: 8263
	at net.minecraft.client.renderer.RegionRenderCache.func_180495_p(RegionRenderCache.java:72)
	at net.optifine.override.ChunkCacheOF.func_180495_p(ChunkCacheOF.java:147)
	at net.minecraft.block.BlockFence.func_176524_e(SourceFile:125)
	at net.minecraft.block.BlockFence.func_176221_a(SourceFile:159)
	at net.minecraft.block.Block.isSideSolid(Block.java:1105)
	at net.minecraft.block.BlockPane.canPaneConnectTo(BlockPane.java:197)
	at net.minecraft.block.BlockPane.func_176221_a(BlockPane.java:44)
	at net.optifine.ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:1648)
	at net.optifine.ConnectedTextures.isNeighbour(ConnectedTextures.java:1615)
	at net.optifine.ConnectedTextures.isNeighbour(ConnectedTextures.java:1595)
	at net.optifine.ConnectedTextures.getConnectedTextureCtmIndex(ConnectedTextures.java:1356)
	at net.optifine.ConnectedTextures.getConnectedTextureCtm(ConnectedTextures.java:825)
	at net.optifine.ConnectedTextures.getConnectedTexture(ConnectedTextures.java:578)
	at net.optifine.ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:400)
	at net.optifine.ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:329)
	at net.optifine.ConnectedTextures.getConnectedTexture(ConnectedTextures.java:123)
	at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:113)
	at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:67)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelFlat(BlockModelRenderer.java:175)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:74)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:53)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:94)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:316)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:38)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.RegionRenderCache.func_180495_p(RegionRenderCache.java:72)
	at net.optifine.override.ChunkCacheOF.func_180495_p(ChunkCacheOF.java:147)
	at net.minecraft.block.BlockFence.func_176524_e(SourceFile:125)
	at net.minecraft.block.BlockFence.func_176221_a(SourceFile:159)
	at net.minecraft.block.Block.isSideSolid(Block.java:1105)
	at net.minecraft.block.BlockPane.canPaneConnectTo(BlockPane.java:197)
	at net.minecraft.block.BlockPane.func_176221_a(BlockPane.java:44)
	at net.optifine.ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:1648)
	at net.optifine.ConnectedTextures.isNeighbour(ConnectedTextures.java:1615)
	at net.optifine.ConnectedTextures.isNeighbour(ConnectedTextures.java:1595)
	at net.optifine.ConnectedTextures.getConnectedTextureCtmIndex(ConnectedTextures.java:1356)
	at net.optifine.ConnectedTextures.getConnectedTextureCtm(ConnectedTextures.java:825)
	at net.optifine.ConnectedTextures.getConnectedTexture(ConnectedTextures.java:578)
	at net.optifine.ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:400)
	at net.optifine.ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:329)
	at net.optifine.ConnectedTextures.getConnectedTexture(ConnectedTextures.java:123)
	at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:113)
	at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:67)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelFlat(BlockModelRenderer.java:175)

-- Block model being tesselated --
Details:
	Block: minecraft:stained_glass[color=green]
	Block location: World: (15,96,59), Chunk: (at 15,6,11 in 0,3; contains blocks 0,0,48 to 15,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Using AO: false
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:74)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:53)

-- Block being tesselated --
Details:
	Block type: ID #95 (tile.stainedGlass // net.minecraft.block.BlockStainedGlass)
	Block data value: 13 / 0xD / 0b1101
	Block location: World: (15,96,59), Chunk: (at 15,6,11 in 0,3; contains blocks 0,0,48 to 15,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:94)

-- Affected level --
Details:
	Level name: MpServer
	All players: 19 total; [EntityPlayerSP['Vxrplxntxr'/1111, l='MpServer', x=-15,09, y=106,00, z=-0,28], EntityOtherPlayerMP['tolpi'/6731, l='MpServer', x=-42,50, y=111,00, z=-1,50], EntityOtherPlayerMP['LeqendKai'/10909, l='MpServer', x=-42,50, y=110,00, z=-4,50], EntityOtherPlayerMP['raiix72'/2355, l='MpServer', x=-42,50, y=110,00, z=1,50], EntityOtherPlayerMP['zVerbauter'/988, l='MpServer', x=-15,50, y=106,00, z=-1,50], EntityOtherPlayerMP['Nxldf'/991, l='MpServer', x=-15,50, y=106,00, z=-1,50], EntityOtherPlayerMP[''/2251, l='MpServer', x=-15,50, y=106,00, z=17,50], EntityOtherPlayerMP['CIT-b727719ba525'/420, l='MpServer', x=-38,50, y=105,00, z=-7,50], EntityOtherPlayerMP['§cPrivate Server'/3784, l='MpServer', x=-0,50, y=106,00, z=-1,50], EntityOtherPlayerMP['§6'/9094, l='MpServer', x=-23,50, y=107,00, z=-16,50], EntityOtherPlayerMP['§6'/7355, l='MpServer', x=-9,50, y=107,00, z=-18,50], EntityOtherPlayerMP['§6'/2872, l='MpServer', x=-11,50, y=107,00, z=-20,50], EntityOtherPlayerMP['§6'/3522, l='MpServer', x=-13,50, y=107,00, z=-21,50], EntityOtherPlayerMP['§6'/9912, l='MpServer', x=-7,50, y=107,00, z=-16,50], EntityOtherPlayerMP['§6'/11946, l='MpServer', x=-19,50, y=107,00, z=-20,50], EntityOtherPlayerMP['§6'/4764, l='MpServer', x=-17,50, y=107,00, z=-21,50], EntityOtherPlayerMP['§6'/11207, l='MpServer', x=-21,50, y=107,00, z=-18,50], EntityOtherPlayerMP['§6'/2482, l='MpServer', x=-5,50, y=107,00, z=-14,50], EntityOtherPlayerMP['§6'/11991, l='MpServer', x=-25,50, y=107,00, z=-14,50]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -16,00,106,00,-2,00 - World: (-16,106,-2), Chunk: (at 0,6,14 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 316974807 game time, 15000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 138 total; [EntityPlayerSP['Vxrplxntxr'/1111, l='MpServer', x=-15,09, y=106,00, z=-0,28], EntityOtherPlayerMP['tolpi'/6731, l='MpServer', x=-42,50, y=111,00, z=-1,50], EntityOtherPlayerMP['LeqendKai'/10909, l='MpServer', x=-42,50, y=110,00, z=-4,50], EntityOtherPlayerMP['raiix72'/2355, l='MpServer', x=-42,50, y=110,00, z=1,50], EntityOtherPlayerMP['zVerbauter'/988, l='MpServer', x=-15,50, y=106,00, z=-1,50], EntityOtherPlayerMP['Nxldf'/991, l='MpServer', x=-15,50, y=106,00, z=-1,50], EntityOtherPlayerMP['IcedBoyOG'/992, l='MpServer', x=-15,50, y=106,00, z=-0,50], EntityOtherPlayerMP['§6'/9094, l='MpServer', x=-23,50, y=107,00, z=-16,50], EntityOtherPlayerMP['§6'/7355, l='MpServer', x=-9,50, y=107,00, z=-18,50], EntityOtherPlayerMP['§6'/2872, l='MpServer', x=-11,50, y=107,00, z=-20,50], EntityOtherPlayerMP['§6'/3522, l='MpServer', x=-13,50, y=107,00, z=-21,50], EntityOtherPlayerMP['§6'/9912, l='MpServer', x=-7,50, y=107,00, z=-16,50], EntityOtherPlayerMP['§6'/11946, l='MpServer', x=-19,50, y=107,00, z=-20,50], EntityOtherPlayerMP['§6'/4764, l='MpServer', x=-17,50, y=107,00, z=-21,50], EntityOtherPlayerMP['§6'/11207, l='MpServer', x=-21,50, y=107,00, z=-18,50], EntityOtherPlayerMP['§6'/2482, l='MpServer', x=-5,50, y=107,00, z=-14,50], EntityOtherPlayerMP['§6'/11991, l='MpServer', x=-25,50, y=107,00, z=-14,50], EntityOtherPlayerMP[''/2251, l='MpServer', x=-15,50, y=106,00, z=17,50], EntityOtherPlayerMP['CIT-b727719ba525'/420, l='MpServer', x=-38,50, y=105,00, z=-7,50], EntityArmorStand['Rüstungsständer'/48, l='MpServer', x=-51,59, y=91,00, z=-63,41], EntityArmorStand['Rüstungsständer'/49, l='MpServer', x=-52,59, y=90,63, z=-62,75], EntityArmorStand['Rüstungsständer'/50, l='MpServer', x=-52,34, y=90,88, z=-63,13], EntityOtherPlayerMP['raiix72'/2355, l='MpServer', x=-42,50, y=110,00, z=1,50], EntityArmorStand['Rüstungsständer'/51, l='MpServer', x=-53,25, y=91,00, z=-63,44], EntityArmorStand['Rüstungsständer'/52, l='MpServer', x=-53,13, y=90,59, z=-62,75], EntityArmorStand['Rüstungsständer'/53, l='MpServer', x=-52,38, y=90,94, z=-63,44], EntityArmorStand['Rüstungsständer'/54, l='MpServer', x=-52,28, y=91,72, z=-63,63], EntityArmorStand['Rüstungsständer'/55, l='MpServer', x=-51,56, y=91,00, z=-63,00], EntityArmorStand['Rüstungsständer'/56, l='MpServer', x=-53,25, y=91,00, z=-63,88], EntityOtherPlayerMP['§6'/2872, l='MpServer', x=-11,50, y=107,00, z=-20,50], EntityArmorStand['Rüstungsständer'/57, l='MpServer', x=-51,72, y=91,69, z=-63,66], EntityArmorStand['Rüstungsständer'/58, l='MpServer', x=-54,31, y=90,00, z=-62,69], EntityArmorStand['Rüstungsständer'/59, l='MpServer', x=-55,13, y=89,59, z=-61,81], EntityArmorStand['Rüstungsständer'/60, l='MpServer', x=-54,19, y=90,00, z=-62,31], EntityArmorStand['Rüstungsständer'/61, l='MpServer', x=-55,00, y=89,88, z=-62,22], EntityArmorStand['Rüstungsständer'/62, l='MpServer', x=-55,66, y=89,59, z=-61,66], EntityArmorStand['Rüstungsständer'/63, l='MpServer', x=-54,50, y=90,69, z=-62,91], EntityArmorStand['Rüstungsständer'/64, l='MpServer', x=-55,13, y=89,94, z=-62,50], EntityArmorStand['Rüstungsständer'/65, l='MpServer', x=-55,94, y=90,00, z=-62,28], EntityArmorStand['Rüstungsständer'/66, l='MpServer', x=-55,06, y=90,72, z=-62,72], EntityArmorStand['Rüstungsständer'/67, l='MpServer', x=-56,06, y=90,00, z=-62,72], EntityArmorStand['§cAHHHHHHHH!!!'/68, l='MpServer', x=-52,47, y=92,03, z=-63,34], EntityArmorStand['§cNEINNNN!!!'/69, l='MpServer', x=-55,06, y=91,13, z=-62,41], EntityOtherPlayerMP['tolpi'/6731, l='MpServer', x=-42,50, y=111,00, z=-1,50], EntityOtherPlayerMP['yUnl3qitMnu'/995, l='MpServer', x=-15,50, y=106,50, z=-1,50], EntityArmorStand['Rüstungsständer'/86, l='MpServer', x=-43,34, y=-2194394,25, z=-61,97], EntityArmorStand['Rüstungsständer'/87, l='MpServer', x=-41,44, y=90,94, z=-50,44], EntityArmorStand['Rüstungsständer'/88, l='MpServer', x=-42,28, y=91,00, z=-50,91], EntityArmorStand['Rüstungsständer'/89, l='MpServer', x=-41,31, y=91,72, z=-50,63], EntityArmorStand['Rüstungsständer'/90, l='MpServer', x=-40,59, y=91,00, z=-49,97], EntityArmorStand['Rüstungsständer'/91, l='MpServer', x=-41,41, y=90,88, z=-50,13], EntityArmorStand['Rüstungsständer'/92, l='MpServer', x=-40,63, y=91,00, z=-50,38], EntityArmorStand['Rüstungsständer'/93, l='MpServer', x=-41,66, y=90,59, z=-49,78], EntityArmorStand['Rüstungsständer'/94, l='MpServer', x=-42,28, y=91,00, z=-50,47], EntityArmorStand['Rüstungsständer'/95, l='MpServer', x=-42,19, y=90,59, z=-49,75], EntityArmorStand['Rüstungsständer'/96, l='MpServer', x=-40,75, y=91,69, z=-50,63], EntityArmorStand['Rüstungsständer'/97, l='MpServer', x=-43,03, y=90,78, z=-50,53], EntityArmorStand['Rüstungsständer'/98, l='MpServer', x=-42,97, y=91,94, z=-50,56], EntityArmorStand['Rüstungsständer'/99, l='MpServer', x=-43,91, y=92,03, z=-50,66], EntityArmorStand['Rüstungsständer'/100, l='MpServer', x=-42,81, y=91,88, z=-50,28], EntityArmorStand['Rüstungsständer'/101, l='MpServer', x=-43,38, y=91,59, z=-49,66], EntityArmorStand['Rüstungsständer'/102, l='MpServer', x=-43,75, y=92,00, z=-50,25], EntityArmorStand['Rüstungsständer'/103, l='MpServer', x=-42,97, y=92,78, z=-50,81], EntityArmorStand['Rüstungsständer'/104, l='MpServer', x=-42,03, y=92,00, z=-50,50], EntityArmorStand['Rüstungsständer'/105, l='MpServer', x=-42,22, y=91,84, z=-50,88], EntityArmorStand['Rüstungsständer'/106, l='MpServer', x=-42,91, y=91,59, z=-49,88], EntityArmorStand['Rüstungsständer'/107, l='MpServer', x=-42,44, y=92,78, z=-51,09], EntityArmorStand['Rüstungsständer'/108, l='MpServer', x=-42,94, y=93,00, z=-50,56], EntityArmorStand['§cAua!'/109, l='MpServer', x=-41,56, y=92,00, z=-48,94], EntityArmorStand['Rüstungsständer'/110, l='MpServer', x=-41,22, y=92,50, z=-48,41], EntityOtherPlayerMP['§cPrivate Server'/3784, l='MpServer', x=-0,50, y=106,00, z=-1,50], EntityArmorStand['Rüstungsständer'/122, l='MpServer', x=-26,03, y=96,69, z=-41,81], EntityArmorStand['Rüstungsständer'/123, l='MpServer', x=-26,94, y=97,00, z=-41,19], EntityArmorStand['Rüstungsständer'/124, l='MpServer', x=-20,63, y=106,00, z=13,78], EntityArmorStand['Rüstungsständer'/125, l='MpServer', x=-18,63, y=106,34, z=18,78], EntityOtherPlayerMP['§6'/9094, l='MpServer', x=-23,50, y=107,00, z=-16,50], EntityOtherPlayerMP['§6'/4764, l='MpServer', x=-17,50, y=107,00, z=-21,50], EntityOtherPlayerMP['LeqendKai'/10909, l='MpServer', x=-42,50, y=110,00, z=-4,50], EntityOtherPlayerMP['PoishSeinVadder'/994, l='MpServer', x=-15,50, y=106,00, z=-1,50], EntityArmorStand['§6BESTE §eSPIELER §6DES §eSERVER´s'/419, l='MpServer', x=-40,63, y=106,25, z=-1,50], EntityOtherPlayerMP['CIT-b727719ba525'/420, l='MpServer', x=-38,50, y=105,00, z=-7,50], EntityArmorStand['§7» §eDatenschutz §7& §eImpressum §7«'/423, l='MpServer', x=-38,50, y=106,78, z=-7,50], EntityArmorStand['Rüstungsständer'/425, l='MpServer', x=-11,50, y=107,16, z=-20,50], EntityArmorStand['§7» §3§lKITPVP §7«'/426, l='MpServer', x=-11,50, y=106,94, z=-20,50], EntityOtherPlayerMP['§6'/11946, l='MpServer', x=-19,50, y=107,00, z=-20,50], EntityArmorStand['§b7 §aSpieler'/427, l='MpServer', x=-11,50, y=106,69, z=-20,50], EntityArmorStand['Rüstungsständer'/428, l='MpServer', x=-23,50, y=107,16, z=-16,50], EntityArmorStand['§7» §6§lJUMP-LEAGUE §7«'/429, l='MpServer', x=-23,50, y=106,94, z=-16,50], EntityArmorStand['§b0 §aSpieler'/430, l='MpServer', x=-23,50, y=106,69, z=-16,50], EntityArmorStand['Rüstungsständer'/431, l='MpServer', x=-21,50, y=107,16, z=-18,50], EntityArmorStand['§7» §e§lKNOCK§f§l-§c§lFFA §7«'/432, l='MpServer', x=-21,50, y=106,94, z=-18,50], EntityArmorStand['§b9 §aSpieler'/433, l='MpServer', x=-21,50, y=106,69, z=-18,50], EntityArmorStand['Rüstungsständer'/434, l='MpServer', x=-19,50, y=107,16, z=-20,50], EntityOtherPlayerMP['§6'/2482, l='MpServer', x=-5,50, y=107,00, z=-14,50], EntityArmorStand['§7» §4§lTTT §7«'/435, l='MpServer', x=-19,50, y=106,94, z=-20,50], EntityArmorStand['§b8 §aSpieler'/436, l='MpServer', x=-19,50, y=106,69, z=-20,50], EntityArmorStand['Rüstungsständer'/437, l='MpServer', x=-17,50, y=107,16, z=-21,50], EntityArmorStand['§7» §e§lSKYWARS §7«'/438, l='MpServer', x=-17,50, y=106,94, z=-21,50], EntityArmorStand['§b0 §aSpieler'/439, l='MpServer', x=-17,50, y=106,69, z=-21,50], EntityArmorStand['Rüstungsständer'/440, l='MpServer', x=-13,50, y=107,16, z=-21,50], EntityOtherPlayerMP['§6'/9912, l='MpServer', x=-7,50, y=107,00, z=-16,50], EntityArmorStand['§7» §c§lBEDWARS §7«'/441, l='MpServer', x=-13,50, y=106,94, z=-21,50], EntityArmorStand['§b5 §aSpieler'/442, l='MpServer', x=-13,50, y=106,69, z=-21,50], EntityArmorStand['Rüstungsständer'/443, l='MpServer', x=-9,50, y=107,16, z=-18,50], EntityOtherPlayerMP['§6'/7355, l='MpServer', x=-9,50, y=107,00, z=-18,50], EntityArmorStand['§7» §6§lMLG-RUSH §7«'/444, l='MpServer', x=-9,50, y=106,94, z=-18,50], EntityArmorStand['§b25 §aSpieler'/445, l='MpServer', x=-9,50, y=106,69, z=-18,50], EntityArmorStand['Rüstungsständer'/446, l='MpServer', x=-7,50, y=107,16, z=-16,50], EntityArmorStand['§7» §a§lGUNGAME §7«'/447, l='MpServer', x=-7,50, y=106,94, z=-16,50], EntityArmorStand['§b28 §aSpieler'/448, l='MpServer', x=-7,50, y=106,69, z=-16,50], EntityArmorStand['Rüstungsständer'/449, l='MpServer', x=-5,50, y=107,16, z=-14,50], EntityArmorStand['§7» §4§lTNT§f§l-§c§lRUN §7«'/450, l='MpServer', x=-5,50, y=106,94, z=-14,50], EntityOtherPlayerMP['§6'/3522, l='MpServer', x=-13,50, y=107,00, z=-21,50], EntityArmorStand['§b5 §aSpieler'/451, l='MpServer', x=-5,50, y=106,69, z=-14,50], EntityArmorStand['Rüstungsständer'/452, l='MpServer', x=-25,50, y=107,16, z=-14,50], EntityArmorStand['§7» §c§lRageMode §7«'/453, l='MpServer', x=-25,50, y=106,94, z=-14,50], EntityArmorStand['§b0 §aSpieler'/454, l='MpServer', x=-25,50, y=106,69, z=-14,50], EntityArmorStand['Rüstungsständer'/198, l='MpServer', x=42,59, y=81,63, z=-53,81], EntityArmorStand['§8» §6§lCHALLENGES §r§8«'/455, l='MpServer', x=-15,50, y=106,00, z=17,50], EntityArmorStand['Rüstungsständer'/199, l='MpServer', x=43,06, y=83,84, z=-54,72], EntityOtherPlayerMP['§6'/11207, l='MpServer', x=-21,50, y=107,00, z=-18,50], EntityArmorStand['§c3. Advent'/456, l='MpServer', x=-15,50, y=105,69, z=17,50], EntityArmorStand['Rüstungsständer'/200, l='MpServer', x=45,63, y=81,69, z=-53,91], EntityOtherPlayerMP['§cPrivate Server'/3784, l='MpServer', x=-0,50, y=106,00, z=-1,50], EntityVillager['§bHaustiertrainer'/457, l='MpServer', x=-39,50, y=105,00, z=5,50], EntityArmorStand['Rüstungsständer'/201, l='MpServer', x=44,78, y=81,56, z=-51,75], EntityArmorStand['Rüstungsständer'/202, l='MpServer', x=40,97, y=81,53, z=-54,91], EntityOtherPlayerMP[''/2251, l='MpServer', x=-15,50, y=106,00, z=17,50], EntityArmorStand['Rüstungsständer'/203, l='MpServer', x=41,97, y=86,03, z=-54,03], EntityArmorStand['Rüstungsständer'/204, l='MpServer', x=43,72, y=85,19, z=-53,41], EntityArmorStand['Rüstungsständer'/205, l='MpServer', x=43,44, y=83,84, z=-52,38], EntityArmorStand['Rüstungsständer'/206, l='MpServer', x=41,69, y=81,63, z=-51,16], EntityArmorStand['Rüstungsständer'/207, l='MpServer', x=43,69, y=81,59, z=-55,84], EntityArmorStand['Rüstungsständer'/208, l='MpServer', x=44,59, y=83,84, z=-52,06], EntityOtherPlayerMP['§6'/11991, l='MpServer', x=-25,50, y=107,00, z=-14,50], EntityOtherPlayerMP['zVerbauter'/988, l='MpServer', x=-15,50, y=106,00, z=-1,50], EntityOtherPlayerMP['Nxldf'/991, l='MpServer', x=-15,50, y=106,00, z=-1,50], EntityOtherPlayerMP['yUnl3qitMnu'/996, l='MpServer', x=-15,50, y=106,00, z=-1,50]]
	Retry entities: 0 total; []
	Server brand: Firefall <- PaperSpigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:402)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:44)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 267859496 bytes (255 MB) / 973078528 bytes (928 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_L5 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	Loaded coremods (and transformers): 
FMLLoadingPlugin (latest.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

**Comment by F0Xde** [comment]
Tritt der Fehler mit gleichem Aufbau aber ohne den Client nicht auf?

**Comment by next361** [comment]
Also, wenn ich ohne Optifine spiele, dann geht es und habe auch schon paar Versionen von Optifine ausprobiert. Habe dann auch gestern mal die neue Version geholt, aber bisher ohne Optifine gestartet.
