### ISSUE TITLE
Minecraft crashed beim starten (mac)

### ISSUE THREAD

**Issue by Icefox06** [HGLabor/client-issues#41]
Wenn ich die mods wie im Tutorial einfüge und dann forge starte crashed mein minecraft. (macOS)
![IMG_0398](https://user-images.githubusercontent.com/76157386/102475954-d03fab80-405a-11eb-8a4e-eab0447a855d.jpeg)

**Comment by Icefox06** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLLoadingPlugin (latest.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 17.12.20 11:55
Description: Initializing game

java.lang.UnsatisfiedLinkError: Unable to load library 'discord-rpc': dlopen(libdiscord-rpc.dylib, 9): image not found
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:169)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:242)
	at com.sun.jna.Library$Handler.<init>(Library.java:140)
	at com.sun.jna.Native.loadLibrary(Native.java:368)
	at com.sun.jna.Native.loadLibrary(Native.java:353)
	at net.arikia.dev.drpc.DiscordRPC$DLL.<clinit>(DiscordRPC.java:226)
	at net.arikia.dev.drpc.DiscordRPC.discordInitialize(DiscordRPC.java:32)
	at de.noriskclient.norisk.module.modules.DiscordRpcModule.<init>(DiscordRpcModule.java:31)
	at de.noriskclient.norisk.NoRiskClient.init(NoRiskClient.java:66)
	at net.minecraft.client.Minecraft.handler$onStartGame$zza000(Minecraft.java:3627)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:497)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:169)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:242)
	at com.sun.jna.Library$Handler.<init>(Library.java:140)
	at com.sun.jna.Native.loadLibrary(Native.java:368)
	at com.sun.jna.Native.loadLibrary(Native.java:353)
	at net.arikia.dev.drpc.DiscordRPC$DLL.<clinit>(DiscordRPC.java:226)
	at net.arikia.dev.drpc.DiscordRPC.discordInitialize(DiscordRPC.java:32)
	at de.noriskclient.norisk.module.modules.DiscordRpcModule.<init>(DiscordRpcModule.java:31)
	at de.noriskclient.norisk.NoRiskClient.init(NoRiskClient.java:66)
	at net.minecraft.client.Minecraft.handler$onStartGame$zza000(Minecraft.java:3627)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:497)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 559291536 bytes (533 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1722 Optifine OptiFine_1.8.9_HD_U_L5 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1722.jar) 
	UCHIJA	Forge{11.15.1.1722} [Minecraft Forge] (forge-1.8.9-11.15.1.1722.jar) 
	Loaded coremods (and transformers): 
FMLLoadingPlugin (latest.jar)
  
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1722
	LWJGL: 2.9.2
	OpenGL: Intel(R) Iris(TM) Plus Graphics 650 GL version 2.1 INTEL-16.1.7, Intel Inc.
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_L5
	OptiFine Build: 20191204-143016
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 INTEL-16.1.7
	OpenGlRenderer: Intel(R) Iris(TM) Plus Graphics 650
	OpenGlVendor: Intel Inc.
	CpuCount: 4
