### ISSUE TITLE
Cosmetics/Resourcen werden nicht geladen

### ISSUE THREAD

**Issue by Mikasaaaaa** [HGLabor/client-issues#42]
Unable to parse metadata section of resourcepack: latest.jar
java.io.FileNotFoundException: C:\Users\Christian%20Admin\AppData\Roaming.minecraft\mods\latest.jar (Das System kann den angegebenen Pfad nicht finden)
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.<init>(ZipFile.java:220)
    at java.util.zip.ZipFile.<init>(ZipFile.java:150)
    at java.util.zip.ZipFile.<init>(ZipFile.java:164)
    at net.minecraft.client.resources.FileResourcePack.func_110599_c(SourceFile:28)
    at net.minecraft.client.resources.FileResourcePack.func_110591_a(SourceFile:36)
    at net.minecraft.client.resources.AbstractResourcePack.func_135058_a(AbstractResourcePack.java:65)
    at net.minecraft.client.resources.LanguageManager.func_135043_a(LanguageManager.java:42)
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:746)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:238)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by 12jking** [comment]
Hast du versucht den Client neu zu Installieren? Hat bei mir auch geklappt.

**Comment by F0Xde** [comment]
Already fixed and duplicate
